version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:11.10
    steps:
        - checkout
        - run:
            name: Install Frontend Environment
            command: cd frontend && npm ci && yarn add --dev jest-junit
        - run:
            name: Install C# Environment
            command: sudo apt-get update && sudo apt-get install -y apt-transport-https && wget https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && sudo dpkg -i packages-microsoft-prod.deb && sudo apt-get update && sudo apt-get install -y dotnet-sdk-3.1
        - run:
            name: Run React tests
            command: mkdir -p test-results/junit && cd frontend && npm run test:ci
            environment:
              JEST_JUNIT_OUTPUT: ../test-results/junit/results.xml
        - store_test_results:
            path: test-results
        - run:
            name: Build C#
            command: dotnet build
        - run:
            name: Test C#
            command: dotnet test --no-build --logger "trx"
        - run:
            name: test results
            command: |
              dotnet tool install -g trx2junit
              export PATH="$PATH:/root/.dotnet/tools"
              trx2junit backend-test/TestResults/*.trx
        - store_test_results:
            path: backend-test/TestResults
            destination: TestResults

