version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:8
    steps:
        - checkout
        - run:
            name: Install dependencies
            command: cd frontend && npm ci
        - run:
            name: Run tests
            command: cd frontend && npm test

